version: '3'
services:
  # dynamodb:
  #   image: amazon/dynamodb-local
  #   ports:
  #     - "8000:8000"
  #   command: "-inMemory -port 8000"
  postgres:
    image: "postgres:16.8-alpine3.20"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=johndoe"
      - "POSTGRES_DB=challengedb"
      - "POSTGRES_PASSWORD=mypassword"
  # minio1:
  #   image: minio/minio
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     MINIO_ACCESS_KEY: "FAKE_ACCESS_KEY"
  #     MINIO_SECRET_KEY: "FAKE_SECRET_ACCESS_KEY"
  #   command: "server /data"
  # mock-api:
  #   image: mock-api:latest
  #   build:
  #     context: ../
  #     dockerfile: mock-api/Dockerfile
  #   volumes:
  #     - ../mock-api:/challenge-api/mock-api
  #   ports:
  #     - "4000:4000"
